{
	"id": "CVE-2023-29824",
	"tags": [
		{
			"label": "Product",
			"message": "n/a"
		},
		{
			"label": "Version",
			"message": "n/a"
		},
		{
			"label": "Vulnerability",
			"message": "n/a"
		}
	],
	"description": " ** DISPUTED ** A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue.",
	"poc": {
		"references": [
			"https://github.com/scipy/scipy/issues/14713",
			"https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565"
		],
		"githubs": [
			"https://github.com/vin01/bogus-cves"
		]
	}
}
