{
	"id": "CVE-2024-32879",
	"tags": [
		{
			"label": "Product",
			"message": "social-app-django"
		},
		{
			"label": "Version",
			"message": "= < 5.4.1 "
		},
		{
			"label": "Vulnerability",
			"message": "CWE-178: Improper Handling of Case Sensitivity"
		},
		{
			"label": "Vulnerability",
			"message": "CWE-303: Incorrect Implementation of Authentication Algorithm"
		}
	],
	"description": " Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
	"poc": {
		"githubs": [
			"https://github.com/fkie-cad/nvd-json-data-feeds"
		]
	}
}
