{
  "id": "CVE-2019-9948",
  "tags": [
    {
      "label": "Product",
      "message": "n/a"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "n/a"
    }
  ],
  "description": " urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
  "poc": {
    "references": [
      "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html",
      "https://bugs.python.org/issue35907"
    ],
    "githubs": [
      "https://github.com/ARPSyndicate/cvemon"
    ]
  }
}
