{
	"id": "CVE-2015-3206",
	"tags": [
		{
			"label": "Product",
			"message": "n/a"
		},
		{
			"label": "Version",
			"message": "= n/a "
		},
		{
			"label": "Vulnerability",
			"message": "n/a"
		}
	],
	"description": " The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.",
	"poc": {
		"references": [
			"https://github.com/apple/ccs-pykerberos/issues/31"
		]
	}
}
