{
  "id": "CVE-2010-3494",
  "tags": [
    {
      "label": "Product",
      "message": "n/a"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "n/a"
    }
  ],
  "description": " Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.",
  "poc": {
    "references": [
      "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
    ]
  }
}
