{
	"id": "CVE-2020-24372",
	"tags": [
		{
			"label": "Product",
			"message": "n/a"
		},
		{
			"label": "Version",
			"message": "n/a"
		},
		{
			"label": "Vulnerability",
			"message": "n/a"
		}
	],
	"description": " LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in lj_err.c.",
	"poc": {
		"references": [
			"https://github.com/LuaJIT/LuaJIT/issues/603"
		]
	}
}
