{
  "id": "CVE-2022-48560",
  "tags": [
    {
      "label": "Product",
      "message": "n/a"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "n/a"
    }
  ],
  "description": " A use-after-free exists in Python through 3.9 via heappushpop in heapq.",
  "poc": {
    "references": [
      "https://bugs.python.org/issue39421"
    ]
  }
}
