{
	"id": "CVE-2022-1289",
	"tags": [
		{
			"label": "Product",
			"message": "Furnace"
		},
		{
			"label": "Version",
			"message": "n/a"
		},
		{
			"label": "Vulnerability",
			"message": "CWE-404 Denial of Service"
		}
	],
	"description": " A denial of service vulnerability was found in tildearrow Furnace. It has been classified as problematic. This is due to an incomplete fix of CVE-2022-1211. It is possible to initiate the attack remotely but it requires user interaction. The issue got fixed with the patch 0eb02422d5161767e9983bdaa5c429762d3477ce.",
	"poc": {
		"references": [
			"https://github.com/tildearrow/furnace/issues/325#issuecomment-1094139655"
		]
	}
}
